# Generated by Django 5.2.3 on 2025-07-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion_tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='Login',
        ),
        migrations.AddField(
            model_name='login',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
